
# # --- Copyright (c) 2024 Linagora
# # licence       : GPL v3
# # - Flavien Perez fperez@linagora.com
# # - Maïlys Jara mjara@linagora.com

include:
 - local: '/gitlab-ci_templates/build-dev.yml'
 - local: '/gitlab-ci_templates/build-doc.yml'
 - local: '/gitlab-ci_templates/build-prod.yml'
 - local: '/gitlab-ci_templates/linter.yml'
 - local: '/gitlab-ci_templates/packages.yml'
 - local: '/gitlab-ci_templates/release.yml'
 - local: '/gitlab-ci_templates/security.yml'
 - local: '/gitlab-ci_templates/tests.yml'
 - local: '/gitlab-ci_templates/sync.yml'

variables:
  PROJECT_PATH: ./gitlab_monitor
  PROJECT_NAME: "gitlab-monitor"
  HARBOR_REGISTRY: "docker-registry.linagora.com"
  IMAGE_CACHE: "gitlab-monitor-dev"
  DOCKER_TLS_CERTDIR: "/certs"
  CACHE_TAG: "1.0.0-dev"
  CODE_SOURCE: "./gitlab_monitor/"
  IMAGE_CACHE_DEPLOY: "gitlab-monitor-deploy-cache"

default:
  tags:
    - stage
  image: $HARBOR_REGISTRY/$PROJECT_NAME/$IMAGE_CACHE:$CACHE_TAG

stages:
  - build
  - test
  - package-build
  - publish
  - production
  - release


# ##################################################################
# #                 BUILD STAGE: BUILD & TESTS                     #
# ##################################################################

build-dev-env:
  stage: build
  extends: .build_dev_env

build-documentation:
  stage: build
  extends: .build_documentation
  needs: []

build-prod-env:
  stage: build
  extends: .build_prod_env
  needs: []

unit_tests:
  stage: build
  extends: .py-pytest

# ##################################################################
# #            TEST STAGE: CODE QUALITY & SECURITY                 #
# ##################################################################

py-lint:
  stage: test
  extends: .py-lint
  needs: []

py-black:
  stage: test
  extends: .py-black
  needs: []

py-isort:
  stage: test
  extends: .py-isort
  needs: []

pycln:
  stage: test
  extends: .pycln
  needs: []

mypy:
  stage: test
  extends: .mypy
  needs: []

py-bandit:
  stage: test
  extends: .py-bandit
  needs: []

py-trivy:
  stage: test
  extends: .py-trivy
  needs: []

slsa-1:
  stage: test
  extends: .slsa-1
  needs: [build-prod-env]

# ##################################################################
# #                    BUILD PACKAGES STAGE                        #
# ##################################################################

build-package:
  stage: package-build
  extends: .build-package
  needs: []

# ##################################################################
# #                   PUBLISH PACKAGES STAGE                       #
# ##################################################################

publish-package:
  stage: publish
  extends: .publish-package
  needs: [build-package]
  when: manual

sync-to-github:
  stage: publish
  extends: .sync-to-github
  when: manual

# ##################################################################
# #                 RELEASE STAGE (CHANGELOGS)                     #
# ##################################################################

prepare:
  stage: release
  extends: .prepare_job
  needs: []

release:
  stage: release
  extends: .release_job
  needs:
    - job: prepare
      artifacts: true

# ##################################################################
# #                 PRODUCTION STAGE -> DEPLOY                     #
# ##################################################################

trigger_multiproject:
  stage: production
  trigger:
    project: linagora/devops/gitlab-manager/gitlab-monitor-deploy
    branch: k8s-deploy
    strategy: depend
  needs: [build-prod-env]
