include:
 - local: '/gitlab-ci_templates/poetry_cache.yml'
 - local: '/gitlab-ci_templates/sphinx_doc.yml'
 - local: '/gitlab-ci_templates/build_app.yml'

variables:
  PROJECT_PATH: ./gitlab_monitor
  HARBOR_REGISTRY: "docker-registry.linagora.com"
  IMAGE_CACHE: "gitlab-monitor/gitlab-monitor-dependencies"
  DOCKER_TLS_CERTDIR: "/certs"
  CACHE_TAG: "1.0.0-dev"

default:
  tags:
    - stage
  image: $HARBOR_REGISTRY/$IMAGE_CACHE:$CACHE_TAG

stages:
  - build
  # - code_quality
  # - test
  # - release

####################################################################
#                           BUILD JOBS                             #
####################################################################

# Stage long qui construit l'image de cache utilisé dans les autres jobs, peut être mis en commentaire si l'image n'a pas subit de changement
# build-cache:
#   extends: build_cache

# build-package:
#   stage: build
#   script:
#     - poetry build -f wheel
#   artifacts:
#     paths:
#       - dist/*.whl

build-documentation:
  extends: build_documentation

build-app:
  extends: build_app

####################################################################
#                       CODE QUALITY JOBS                          #
####################################################################

# linter_code_quality:
#   extends: .linter # a revoir avec le .tests pour trivy et bandit

# ####################################################################
# #                            TEST JOBS                             #
# ####################################################################

# unit_tests:
#   extends: .tests # a revoir

# ####################################################################
# #                       DEPLOY/RELEASE JOBS                        #
# ####################################################################

# k8s-deploy:
#   extends: .k8s_deploy # a implémenter