include:
 - local: '/gitlab-ci_templates/poetry_cache.yml'

variables:
  PROJECT_PATH: ./gitlab_monitor
  IMAGE: $HARBOR_IMAGE #récupérer l'image sur harbor (image du poetry cache)

default:
  tags:
    - docker
  image: $IMAGE

stages:
  - build
  # - code_quality
  # - test
  # - release

####################################################################
#                           BUILD JOBS                             #
####################################################################

#construire l'image docker pour le cache
build-cache:
  extends: .poetry_cache

# build-package:
#   stage: build
#   script:
#     - poetry build -f wheel
#   artifacts:
#     paths:
#       - dist/*.whl

build-documentation:
  extends: .sphinx_doc

build-app:
  extends: .build_app
  needs: ["build_dependencies"]

####################################################################
#                       CODE QUALITY JOBS                          #
####################################################################

# linter_code_quality:
#   extends: .linter # a revoir avec le .tests pour trivy et bandit

# ####################################################################
# #                            TEST JOBS                             #
# ####################################################################

# unit_tests:
#   extends: .tests # a revoir

# ####################################################################
# #                       DEPLOY/RELEASE JOBS                        #
# ####################################################################

# k8s-deploy:
#   extends: .k8s_deploy # a implémenter