
# # --- Copyright (c) 2024 Linagora
# # licence       : Apache 2.0
# # - Flavien Perez fperez@linagora.com
# # - Maïlys Jara mjara@linagora.com

include:
 - local: '/gitlab-ci_templates/build-dev.yml'
 - local: '/gitlab-ci_templates/build-doc.yml'
 - local: '/gitlab-ci_templates/build-prod.yml'
 - local: '/gitlab-ci_templates/linter.yml'


variables:
  PROJECT_PATH: ./gitlab_monitor
  HARBOR_REGISTRY: "docker-registry.linagora.com"
  IMAGE_CACHE: "gitlab-monitor/gitlab-monitor-dev"
  DOCKER_TLS_CERTDIR: "/certs"
  CACHE_TAG: "1.0.0-dev"

default:
  tags:
    - stage
  image: $HARBOR_REGISTRY/$IMAGE_CACHE:$CACHE_TAG

stages:
  - build
  - code_quality
  # - test
  # - release

####################################################################
#                           BUILD JOBS                             #
####################################################################

# Stage long qui construit l'image de cache utilisé dans les autres jobs, peut être mis en commentaire si l'image n'a pas subit de changement
build-dev-env:
  stage: build
  extends: .build_dev_env

build-documentation:
  stage: build
  extends: .build_documentation
  needs: []

build-prod-env:
  stage: build
  extends: .build_prod_env
  needs: []

# build-package:
#   stage: build
#   script:
#     - poetry build -f wheel
#   artifacts:
#     paths:
#       - dist/*.whl
#   needs: []

####################################################################
#                       CODE QUALITY JOBS                          #
####################################################################

py-lint:
  stage: code_quality
  extends: .py-lint

py-black:
  stage: code_quality
  extends: .py-black

py-isort:
  stage: code_quality
  extends: .py-isort

pycln:
  stage: code_quality
  extends: .pycln

mypy:
  stage: code_quality
  extends: .mypy

# ####################################################################
# #                            TEST JOBS                             #
# ####################################################################

# unit_tests:
#   extends: .tests # a revoir

# ####################################################################
# #                       DEPLOY/RELEASE JOBS                        #
# ####################################################################

# k8s-deploy:
#   extends: .k8s_deploy # a implémenter