# Image that builds the app/source code

FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt ./

RUN apk add --no-cache libpq wget && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
    pip install --upgrade pip && \
    apk del .build-deps

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Add a non-root user
RUN adduser -D myuser
USER myuser

# Définir le CMD pour démarrer un shell interactif
CMD ["/bin/bash"]