# Image that builds the app/source code

FROM python:3.12-slim-bullseye

WORKDIR /app

COPY . /app

# Add a non-root user
RUN useradd -m myuser
USER myuser

# Start the application
# CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]