# Image docker contenant les sources du projet python utilisé afin d'optimiser la 
# vitesse d'éxécution d'une pipeline.

FROM python:3.11.4-slim-bullseye AS builder
WORKDIR /app
ENV POETRY_HOME="/opt/poetry"
ENV VIRTUAL_ENV="/opt/project"
ENV PATH="$VIRTUAL_ENV/bin:$POETRY_HOME/bin:$PATH"

LABEL licence="EUPL"
LABEL description="Image servant de cache pour les dépendances du projet"
LABEL equipe="Flavien Perez, Maïlys Jara"
LABEL version="1.0.0"

COPY ./pyproject.toml .

RUN apt update &&\
    apt install --no-install-recommends -y \
    build-essential \
    libffi-dev \
    libssh-dev \
    python3-dev \
    git && \
    python3 -m venv $VIRTUAL_ENV && \
    pip install --no-cache-dir \
    poetry==1.8.4 \ 
    setuptools==65.3.0 \
    pip==22.2.2 --upgrade && \
    poetry install --no-root

RUN pip install --no-cache-dir \
    sphinx \
    sphinx-rtd-theme \
    sphinx-autodoc-typehints

RUN wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/' | xargs -I {} wget https://github.com/aquasecurity/trivy/releases/download/v{}/trivy_{VERSION}_Linux-64bit.tar.gz && \
    tar -zxvf trivy_${VERSION}_Linux-64bit.tar.gz && \
    mv trivy /usr/local/bin/ && \
    rm trivy_${VERSION}_Linux-64bit.tar.gz


CMD ["/bin/bash"]