build_app:
  stage: build
  services:
    - docker:24.0.5-dind
  variables:
    DEPENDENCIES_IMAGE: "gitlab-monitor-dependencies"
    IMAGE_NAME: "gitlab-monitor-app"
    DOCKERFILE: "Dockerfile.app"
    HARBOR_URL: "docker-registry.linagora.com"
    PROJECT_NAME: "gitlab-monitor"
    APP_TAG: "1.0.0-dev"
  before_script:
    - docker info
  script:
    - docker login -u ${HARBOR_LOGIN} -p ${HARBOR_PSW} $HARBOR_URL
    - docker pull $DEPENDENCIES_IMAGE:$APP_TAG
    - docker build --build-arg $DEPENDENCIES_IMAGE:$APP_TAG -t $IMAGE_NAME:$APP_TAG -f $DOCKERFILE .
    - docker tag $IMAGE_NAME:$APP_TAG $HARBOR_URL/$PROJECT_NAME/$IMAGE_NAME:$APP_TAG
    - docker push $HARBOR_URL/$PROJECT_NAME/$IMAGE_NAME:$APP_TAG