
# # --- Copyright (c) 2024 Linagora
# # licence       : Apache 2.0
# # - Flavien Perez fperez@linagora.com
# # - Maïlys Jara mjara@linagora.com

py-lint:
  stage: code_quality
  image: $IMAGE
  script:
    - pip install pylint
    - pylint --output-format=colorized $PROJECT_PATH

py-black:
  stage: code_quality
  image: $IMAGE
  script:
    - black $PROJECT_PATH --check --diff

py-isort:
  image: $IMAGE
  stage: code_quality
  script:
    - isort $PROJECT_PATH --check-only --profile=black

pycln:
  image: $IMAGE
  stage: code_quality
  script:
    - pycln $PROJECT_PATH

mypy:
  image: $IMAGE
  stage: code_quality
  script:
    - mypy $PROJECT_PATH --junit-xml report_mypy.xml
  artifacts:
    reports:
      junit: report_mypy.xml

# a ajouter dans un stage sécurité avec slsa niveau 1 (available provenance)
bandit:

trivy: