
# # --- Copyright (c) 2024 Linagora
# # licence       : GPL v3
# # - Flavien Perez fperez@linagora.com
# # - Maïlys Jara mjara@linagora.com


.build-package:
  before_script:
    - poetry --version
  script:
    - poetry build
  artifacts:
    paths:
      - dist/*.whl

.publish-package:
  before_script:
    - twine --version
  script:
    - rm -rf dist/*
    - poetry build
    - twine upload -u $NEXUS_PYPI_BOT_USERNAME -p $NEXUS_PYPI_BOT_PASSWORD --repository-url $NEXUS_PYPI_URL dist/*