
# # --- Copyright (c) 2024 Linagora
# # licence       : GPL v3
# # - Flavien Perez fperez@linagora.com
# # - Maïlys Jara mjara@linagora.com

.build-package:
  before_script:
    - poetry --version
  script:
    - poetry build
  artifacts:
    paths:
      - dist/*.whl

.publish-package:
  before_script:
    - twine --version
    - wheel version
  script:
    - rm -rf dist/* # good practice : au lieu de cette ligne changer le "dist/*" plus bas
    
    # - python3 ./scripts/setup_package.py sdist bdist_wheel
    - poetry build
    - ls dist/
    - twine upload -u $NEXUS_PYPI_BOT_USERNAME -p $NEXUS_PYPI_BOT_PASSWORD --repository-url $NEXUS_PYPI_URL dist/* #dist/nom_du_fichier_version-concernée.whl