build_cache:
  image: docker:24.0.5
  stage: build
  services:
    - docker:24.0.5-dind
  variables:
    IMAGE_NAME: "gitlab-monitor-dependencies"
    DOCKERFILE: "Dockerfile.dependencies"
    HARBOR_URL: "docker-registry.linagora.com"
    PROJECT_NAME: "gitlab-monitor"
  before_script:
    - docker info
  script:
    - docker build -t $IMAGE_NAME:$CACHE_TAG -f $DOCKERFILE .
    - docker login -u ${HARBOR_LOGIN} -p ${HARBOR_PSW} $HARBOR_URL
    - docker tag $IMAGE_NAME:$CACHE_TAG $HARBOR_URL/$PROJECT_NAME/$IMAGE_NAME:$CACHE_TAG
    - docker push $HARBOR_URL/$PROJECT_NAME/$IMAGE_NAME:$CACHE_TAG