build_cache:
  image: docker:stable
  stage: build
  services:
    - name: docker:19.03.12-dind
      command: ["--tls=false"]
  variables:
    IMAGE_NAME: "gitlab-monitor-dependencies"
    DOCKERFILE: "Dockerfile.dependencies"
    HARBOR_URL: "docker-registry.linagora.com"
    PROJECT_NAME: "gitlab-monitor"
    TAG: "1.0.0-dev"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apt-get update && apt-get install -y apt-transport-https
    - docker info
  script:
    - docker build -t $IMAGE_NAME -f $DOCKERFILE .
    - docker login -u ${HARBOR_LOGIN} -p ${HARBOR_PSW} $HARBOR_URL
    - docker tag $IMAGE_NAME:$TAG $HARBOR_URL/$PROJECT_NAME/$IMAGE_NAME:$TAG
    - docker push $HARBOR_URL/$PROJECT_NAME/$IMAGE_NAME:$TAG
  docker:
    privileged: true