build_cache:
  image: docker:stable
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_NAME: "gitlab-monitor-dependencies"
    DOCKERFILE: "Dockerfile.dependencies"
    HARBOR_URL: "docker-registry.linagora.com"
    PROJECT_NAME: "gitlab-monitor"
    TAG: "1.0.0-dev"
  script:
    - docker build -t $IMAGE_NAME -f $DOCKERFILE .
    - docker login -u ${HARBOR_LOGIN} -p ${HARBOR_PSW} $HARBOR_URL
    - docker tag $IMAGE_NAME:$TAG $HARBOR_URL/$PROJECT_NAME/$IMAGE_NAME:$TAG
    - docker push $HARBOR_URL/$PROJECT_NAME/$IMAGE_NAME:$TAG