
# # --- Copyright (c) 2024 Linagora
# # licence       : GPL v3
# # - Flavien Perez fperez@linagora.com
# # - Maïlys Jara mjara@linagora.com


# TODO: personaliser ces 2 jobs
.prepare_job:
  # rules:
  # - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - echo "CI_API_URL $CI_API_URL"
    - echo "CI_PROJECT_ID $CI_PROJECT_ID"
    - echo "CI_COMMIT_TAG $CI_COMMIT_TAG"
    - 'curl -H "PRIVATE-TOKEN: $CI_API_TOKEN" "$CI_API_URL/api/v4/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG" | jq -r .notes > release_notes.md'
  artifacts:
    paths:
    - release_notes.md

.release_job:
  # rules:
  # - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Creating release"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: release_notes.md
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
    # assets: # TODO: récupérer le code source sur nexus + lien vers le site du projet
    #   links:
    #     - name: 'Container Image $CI_COMMIT_TAG'
    #       url: "https://$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"