
# # --- Copyright (c) 2024 Linagora
# # licence       : Apache 2.0
# # - Flavien Perez fperez@linagora.com
# # - Maïlys Jara mjara@linagora.com
.py-bandit:
  before_script:
    - bandit --version
  script:
    - bandit -c pyproject.toml -r $CI_PROJECT_PATH -f xml -o bandit_report.xml
  artifacts:
    reports:
      junit: bandit_report.xml

.py-trivy:
  before_script:
    - poetry --version
    - trivy --version
  script:
    - poetry export -f requirements.txt --without-hashes --output reports/requirements.txt
    - ls $CI_PROJECT_PATH
    - trivy fs --scanners vuln,secret,config $CI_PROJECT_PATH -o report_trivy.json
  artifacts:
    paths:
      - report_trivy.json

.slsa-1:
  script:
    - echo "commit SHA actuel est $CI_COMMIT_SHA, id du pipeline $CI_PIPELINE_ID"
#ajouter un script de verification des provenances comme dans task-manager