
# # --- Copyright (c) 2024 Linagora
# # licence       : GPL v3
# # - Flavien Perez fperez@linagora.com
# # - Maïlys Jara mjara@linagora.com






.py-bandit:
  before_script:
    - bandit --version
  script:
    - bandit -c pyproject.toml -r $CODE_SOURCE -f xml -o bandit_report.xml
  artifacts:
    reports:
      junit: bandit_report.xml

.py-trivy:
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  before_script:
    - trivy --version
  script:
    - trivy fs --scanners vuln,secret,config $CODE_SOURCE -o report_trivy.json
  artifacts:
    paths:
      - report_trivy.json

.slsa-1:
  script:
    - echo "commit SHA actuel est $CI_COMMIT_SHA, id du pipeline $CI_PIPELINE_ID"
    - ./scripts/verify_provenances.sh
  needs:
    - build-prod-env